### ISSUE TITLE
+= en ++ of -= en --

### ISSUE THREAD

**Issue by zuja12** [MauriceBorrel/Arduino-Projects#3]
https://github.com/MauriceBorrel/Arduino-Projects/blob/f24b9156081d6b794e86913bd65be74a4f711adc/Potmeter/Potmeter.ino#L40
Zane had je dit al aangegeven. Hij heeft gelijk, want het komt best veel voor dat je bovenstaande optel en aftrek methoden niet gebruikt.
Verstandig dat je dit aanpast en er ook een gewoonte van maakt. Want eigenlijk geldt dit voor bijna elke taal.

**Comment by MauriceBorrel** [comment]
Zane vertelde dit inderdaad al. Het is inmiddels aangepast.
